SCALE Job started on Thu 14/11/2024 14:09:28
With Host name LAPTOP-CIORRL13
working directory C:\Users\Jonathon\AppData\Local\Temp\scale.Jonathon.12092
and process id 12092.
Input file named \\wsl$\Ubuntu-20.04\home\moosetools\projects\SCALETools\SCALESlice\tests\cylinder_in_a_box\cylinder_in_a_box.inp
and output file named \\wsl$\Ubuntu-20.04\home\moosetools\projects\SCALETools\SCALESlice\tests\cylinder_in_a_box\cylinder_in_a_box.out
##########################################################
***Created 4 infinite homogeneous cells from unreferenced mixtures.



 MAVRIC, part  1, reading/checking detailed input                             
 *******************************************************************************

  error in opening binary concentration file: HC5.f71
  error in opening binary concentration file: HC5.f71
